"use client";
import { useEffect, useRef, useState } from "react";
import styles from "./instructor-carousel.module.css";
import type { CarouselInstructor as Instructor } from "@/lib/instructor-defaults";
function Portrait({person}:{person:Instructor}){const [x,y,w,h]=person.crop??[0,0,person.width,person.height];const scale=Math.min(300/w,400/h);const picture=<svg x={(300-w*scale)/2} y={(400-h*scale)/2} width={w*scale} height={h*scale} viewBox={[x,y,w,h].join(" ")} overflow="hidden"><image href={person.photo} width={person.width} height={person.height}/></svg>;return <span className={styles.portrait}><svg className={styles.blur} viewBox="0 0 300 400" aria-hidden="true">{picture}</svg><svg className={styles.photo} viewBox="0 0 300 400" role="img" aria-label={person.name}>{picture}</svg></span>}
export function InstructorCarousel({instructors}:{instructors:Instructor[]}){const[step,setStep]=useState(0);const[paused,setPaused]=useState(false);const[hover,setHover]=useState(false);const[focused,setFocused]=useState(false);const[reduced,setReduced]=useState(false);const[active,setActive]=useState<Instructor|null>(null);const touch=useRef<{x:number;y:number}|null>(null);const suppressClick=useRef(false);const dialog=useRef<HTMLDialogElement>(null);const index=((step%instructors.length)+instructors.length)%instructors.length;const stopped=paused||hover||focused||reduced||!!active;
useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");const sync=()=>setReduced(media.matches);sync();media.addEventListener("change",sync);return()=>media.removeEventListener("change",sync)},[]);
useEffect(()=>{if(stopped)return;const timer=window.setInterval(()=>{if(!document.hidden)setStep(s=>s+1)},8000);return()=>window.clearInterval(timer)},[stopped,step]);
useEffect(()=>{if(!active)return;const el=dialog.current;el?.showModal();const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{el?.close();document.body.style.overflow=previous}},[active]);
if(!instructors.length)return null;
return <section id="instructors" className={styles.section} aria-labelledby="instructors-title" aria-roledescription="carousel" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setFocused(false)}}>
<div className={styles.heading}><p className="landing-eyebrow">THE PEOPLE BEHIND THE STEPS</p><h2 id="instructors-title">Click to Meet the Instructor</h2></div>
<div className={styles.stage} aria-live={stopped?"polite":"off"} onTouchStart={e=>{if(e.touches.length!==1){touch.current=null;return}touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY};suppressClick.current=false}} onTouchCancel={()=>{touch.current=null}} onTouchEnd={e=>{const start=touch.current;touch.current=null;if(!start)return;const dx=e.changedTouches[0].clientX-start.x;const dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.5){suppressClick.current=true;setStep(s=>s+(dx<0?1:-1))}}} onClickCapture={e=>{if(suppressClick.current){e.preventDefault();e.stopPropagation();suppressClick.current=false}}}>
<button className={styles.edge+" "+styles.left} aria-label="Previous instructor" onClick={()=>setStep(s=>s-1)}>‹</button><button className={styles.edge+" "+styles.right} aria-label="Next instructor" onClick={()=>setStep(s=>s+1)}>›</button>
{instructors.map((person,i)=><article key={person.name} className={styles.slide} aria-hidden={i!==index} inert={i!==index} style={{visibility:i===index?"visible":"hidden"}} aria-roledescription="slide" aria-label={`${i+1} of ${instructors.length}`}><button className={styles.photoButton} onClick={()=>setActive(person)} aria-label={"Meet "+person.name}><Portrait person={person}/><span className={styles.nameOverlay}>{person.name}</span></button></article>)}
</div><div className={styles.controls}><div className={styles.dots} aria-label="Choose instructor">{instructors.map((person,i)=><button key={person.name} className={styles.dot} aria-label={"Show "+person.name} aria-current={i===index?"true":undefined} onClick={()=>setStep(s=>s+(i-index))}><span/></button>)}</div>{!reduced&&<button className={styles.pause} aria-label={paused?"Play instructor carousel":"Pause instructor carousel"} aria-pressed={paused} onClick={()=>setPaused(p=>!p)}>{paused?"▷":"Ⅱ"}</button>}</div>
<dialog ref={dialog} className={styles.modal} onCancel={()=>setActive(null)} onClose={()=>setActive(null)} onClick={e=>{if(e.target===e.currentTarget)setActive(null)}} aria-labelledby="instructor-modal-name">{active&&<div className={styles.modalInner}><button className={styles.close} aria-label="Close instructor profile" onClick={()=>setActive(null)}>×</button><div className={styles.modalPhoto}><Portrait person={active}/></div><div className={styles.modalBio}><p className={styles.label}>DANCE INSTRUCTOR</p><h2 id="instructor-modal-name">{active.name}</h2><p>{active.bio}</p></div></div>}</dialog></section>}
