"use server";
import {revalidatePath} from "next/cache"; import {redirect} from "next/navigation"; import {z} from "zod"; import {createClient} from "@/lib/supabase/server"; import {requireViewer,isStaff} from "@/lib/auth"; import {sendEmail} from "@/lib/providers/email"; import {sendSms} from "@/lib/providers/sms";

async function staff(){const viewer=await requireViewer();if(!isStaff(viewer.roles))throw new Error("Manager access required.");return {viewer,supabase:(await createClient())!};}
const uuid=z.string().uuid();
export async function bookSession(fd:FormData){const viewer=await requireViewer();const sessionId=uuid.parse(fd.get("session_id"));const supabase=(await createClient())!;const consent=fd.get("sms_consent")==="yes";if(consent)await supabase.from("communication_consents").upsert({user_id:viewer.user.id,channel:"sms",status:"opted_in",consented_at:new Date().toISOString(),source:"class_booking"},{onConflict:"user_id,channel"});const {data,error}=await supabase.rpc("register_for_session",{p_session_id:sessionId});if(error)redirect(`/dashboard?error=${encodeURIComponent(error.message)}`);const {data:registration}=await supabase.from("registrations").select("id,status,class_sessions(starts_at,class_types(name))").eq("session_id",sessionId).eq("user_id",viewer.user.id).single();const session=(registration?.class_sessions as any);const subject=`${data==="waitlisted"?"Waitlist":"Class"} confirmation: ${session?.class_types?.name||"Spurs Over Stetsons"}`;const message=`Hi ${viewer.profile?.full_name||"there"}, your status is ${data} for ${session?.class_types?.name||"your class"} on ${session?.starts_at?new Date(session.starts_at).toLocaleString():"the scheduled date"}.`;if(viewer.profile?.email&&registration){const result=await sendEmail({to:viewer.profile.email,subject,message,idempotencyKey:`registration-${registration.id}-email`});await supabase.from("communication_logs").insert({session_id:sessionId,registration_id:registration.id,user_id:viewer.user.id,channel:"email",recipient_address:viewer.profile.email,subject,body:message,message_type:"booking_confirmation",status:result.ok?"sent":"failed",provider_message_id:result.providerId||null,error_message:result.error||null,created_by:viewer.user.id,sent_at:result.ok?new Date().toISOString():null});}if(consent&&viewer.profile?.phone&&registration){const result=await sendSms({to:viewer.profile.phone,message});await supabase.from("communication_logs").insert({session_id:sessionId,registration_id:registration.id,user_id:viewer.user.id,channel:"sms",recipient_address:viewer.profile.phone,body:message,message_type:"booking_confirmation",status:result.ok?"sent":"failed",provider_message_id:result.providerId||null,error_message:result.error||null,created_by:viewer.user.id,sent_at:result.ok?new Date().toISOString():null});}redirect(`/dashboard?booking=${data}`);}
export async function cancelRegistration(fd:FormData){const supabase=(await createClient())!;const {error}=await supabase.rpc("cancel_my_registration",{p_registration_id:uuid.parse(fd.get("registration_id"))});if(error)redirect(`/dashboard?error=${encodeURIComponent(error.message)}`);revalidatePath("/dashboard");}
export async function saveAvailability(fd:FormData){await requireViewer();const supabase=(await createClient())!;const row={instructor_id:uuid.parse(fd.get("instructor_id")),starts_at:z.string().min(1).parse(fd.get("starts_at")),ends_at:z.string().min(1).parse(fd.get("ends_at")),notes:String(fd.get("notes")||"")};const {error}=await supabase.from("instructor_availability").insert(row);if(error)throw new Error(error.message);revalidatePath("/dashboard/availability");}
export async function saveClassType(fd:FormData){const {supabase}=await staff();const row={name:z.string().min(2).parse(fd.get("name")),level:String(fd.get("level")||""),duration_minutes:z.coerce.number().min(15).parse(fd.get("duration_minutes")),default_capacity:z.coerce.number().int().min(1).parse(fd.get("default_capacity")),default_price_cents:Math.round(z.coerce.number().min(0).parse(fd.get("price"))*100)};const {error}=await supabase.from("class_types").insert(row);if(error)throw new Error(error.message);revalidatePath("/dashboard/class-types");}
export async function saveSession(fd:FormData){const {supabase,viewer}=await staff();const row={class_type_id:uuid.parse(fd.get("class_type_id")),instructor_id:uuid.parse(fd.get("instructor_id")),starts_at:z.string().min(1).parse(fd.get("starts_at")),ends_at:z.string().min(1).parse(fd.get("ends_at")),capacity:z.coerce.number().int().min(1).parse(fd.get("capacity")),price_cents:Math.round(z.coerce.number().min(0).parse(fd.get("price"))*100),location:String(fd.get("location")||""),status:z.enum(["draft","published"]).parse(fd.get("status")),created_by:viewer.user.id};const {error}=await supabase.from("class_sessions").insert(row);if(error)throw new Error(error.message);revalidatePath("/dashboard/schedule");revalidatePath("/schedule");}
export async function setAttendance(fd:FormData){const {supabase}=await staff();const {error}=await supabase.from("registrations").update({attendance_status:z.enum(["present","absent","excused","unmarked"]).parse(fd.get("attendance_status"))}).eq("id",uuid.parse(fd.get("registration_id")));if(error)throw new Error(error.message);revalidatePath("/dashboard/registrations");}
export async function manageRegistration(fd:FormData){const {supabase}=await staff();const {error}=await supabase.rpc("manage_registration",{p_registration_id:uuid.parse(fd.get("registration_id")),p_action:z.enum(["cancel","promote"]).parse(fd.get("action"))});if(error)throw new Error(error.message);revalidatePath("/dashboard/registrations");revalidatePath("/schedule");}
export async function saveInstructor(fd:FormData){const {supabase}=await staff();const {error}=await supabase.from("instructors").update({bio:String(fd.get("bio")||""),dance_styles:String(fd.get("dance_styles")||"").split(",").map(x=>x.trim()).filter(Boolean),active:fd.get("active")==="true"}).eq("id",uuid.parse(fd.get("instructor_id")));if(error)throw new Error(error.message);revalidatePath("/dashboard/instructors");revalidatePath("/instructors");}
export async function setSessionStatus(fd:FormData){const {supabase}=await staff();const {error}=await supabase.from("class_sessions").update({status:z.enum(["draft","published","cancelled","completed"]).parse(fd.get("status"))}).eq("id",uuid.parse(fd.get("session_id")));if(error)throw new Error(error.message);revalidatePath("/dashboard/schedule");revalidatePath("/schedule");}
